name: dart_fundamentals
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  path: ^1.8.0
  characters: ^1.1.0
  http: ^0.13.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
